# Generated by Django 2.2.9 on 2020-01-02 01:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20191219_0336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_date',
            field=models.DateTimeField(default=datetime.datetime(2020, 1, 2, 1, 22, 53, 67896, tzinfo=utc)),
        ),
    ]
